- name: Execute commands playbook
  hosts: httpd
  become: true
  tasks:
    - name: Update system packages
      yum:
        name: '*'
        state: latest
      become: true

    - name: Install git package
      yum:
        name: git
        state: present
      become: true

    - name: Install python3-pip package
      yum:
        name: python3-pip
        state: present
      become: true

    - name: Clone repository
      git:
        repo: https://github.com/Orelbaz/Sela-course.git
        dest: /Sela-course
        version: main
      become: true

    - name: Change directory
      shell: cd /Sela-course/alpaca-flask/
      become: true

    - name: Install Python dependencies
      pip:
        requirements: /Sela-course/alpaca-flask/requirements.txt
        state: present
      become: true

    - name: Install Flask
      pip:
        name: flask
        state: present
      become: true

    - name: Create Flask systemd service
      template:
        src: flask.service.j2
        dest: /etc/systemd/system/flask.service
      become: true
      notify:
        - Reload systemd

    - name: Start and enable Flask service
      systemd:
        name: flask
        state: started
        enabled: yes
      become: true

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
      become: true